# Generated by Django 3.2.9 on 2021-12-01 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joby', '0002_auto_20211201_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('position_name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=900)),
                ('company', models.CharField(max_length=250)),
                ('timetamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joby.city')),
                ('dev_langauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joby.devlanguage')),
            ],
        ),
    ]
