# Generated by Django 3.2.9 on 2021-12-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joby', '0003_vacancies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancies',
            new_name='Vacancy',
        ),
    ]
